### PR TITLE
Fix incorrect size output

### PR DESCRIPTION
**Pull request by ntomita**
1. Fixing outputting incorrect image size issue
2. Set memorable variable names

For the first issue, the previous code generated images with wrong dimension (see attached). This change fix the issue, make it more memory efficient, and improves maintainability of the code.

TCGA-2Z-A9J3-01Z-00-DX1 6B0E7DF6-733D-4007-84A3-E67BBC4966A6 svs_fuse

### CODE REVIEW

**Comment by choosehappy** [comment]
Thank you for your contribution! @nanli-emory can you take a look?

**Comment by nanli-emory** [comment]
Hi @ntomita and @choosehappy , I merged the code into PR #234

**Comment by choosehappy** [comment]
Thanks, @ntomita would you mind confirming that it works for you as expected?

**Comment by ntomita** [comment]
@choosehappy Yes, I checked a few slides and it seems working as expected now. Should I close this PR now?

**Comment by choosehappy** [comment]
Great! If you're happy I'm happy :)  please feel free to close

On 23/02/2023 16:56, Naofumi Tomita wrote:

@choosehappy<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fchoosehappy&data=05%7C01%7Candrew.r.janowczyk%40emory.edu%7Cafedd78024e64d392c6308db15b68602%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C638127645919041144%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DZidWnRZc6Lg%2Fpx1MF79dJNeS8jeDCNUSRFgv0bJ8sc%3D&reserved=0> Yes, I checked a few slides and it seems working as expected now. Should I close this PR now?

**Pull request closed without merging**
