### PR TITLE
fix #315 - BasicModule.countTissuePieces does not define the `params` parameter 

### LINKED ISSUE #315: countTissuePieces() takes 1 positional argument but 2 were given
I am trying to run HistoQC on a dataset but I am getting: 

> 2024-08-14 18:03:37,380 - WARNING - HS14-29933 1A .ndpi - Mask file '/opt/HistoQC/.histoqc_pkg_data_tmpk_mr7_8v/./pen/1k_version/pen_black_mask.png' is not a binary image. Automatically converting to binary...
> 2024-08-14 18:09:02,260 - ERROR - /data/HS14-29933 1A .ndpi - Error analyzing file (skipping): 	 <class 'TypeError'> Inappropriate argument type. countTissuePieces() takes 1 positional argument but 2 were given
> 2024-08-14 18:16:22,410 - ERROR - /data/HS16-26406 2A .ndpi - Error analyzing file (skipping): 	 <class 'TypeError'> Inappropriate argument type. countTissuePieces() takes 1 positional argument but 2 were given
> 2024-08-14 18:17:11,626 - ERROR - /data/HS12-32993 2A .ndpi - Error analyzing file (skipping): 	 <class 'TypeError'> Inappropriate argument type. countTissuePieces() takes 1 positional argument but 2 were given......

How to resolve this

### PR DESCRIPTION
**Pull request by nanli-emory**
add `params` parameter at second position in BasicModule.countTissuePieces to fix the #315 issue

### CODE REVIEW

**Comment by jacksonjacobs1** [comment]
Thanks Nan. 

Looks like our unit tests will attempt to run `countTissuePieces()`, but the target .tsv file does not include a column for # tissue pieces. Can you update the target results.tsv and confirm that this commit passes unit tests?

**Comment by nanli-emory** [comment]
> Thanks Nan.
> 
> Looks like our unit tests will attempt to run `countTissuePieces()`, but the target .tsv file does not include a column for # tissue pieces. Can you update the target results.tsv and confirm that this commit passes unit tests?

Hi @jacksonjacobs1 I added  # tissue pieces field into target/results.tsv and modified the test code, please review it.

**Comment by jacksonjacobs1** [comment]
Thanks.

Can you confirm that the unit tests run successfully? Also, does the coverage report need to be regenerated? Ideally this should be done in a github action but for now needs to be done manually.

**Comment by nanli-emory** [comment]
> Thanks.
> 
> Can you confirm that the unit tests run successfully? Also, does the coverage report need to be regenerated? Ideally this should be done in a github action but for now needs to be done manually.

Hi @jacksonjacobs1 , I ran it on my local and updated the new coverage report. Please check.
Screenshot from 2024-08-22 10-18-07

**Comment by jacksonjacobs1** [comment]
Great, thanks. This PR can be merged.

**Pull request merged**
